name: chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

env:
  MIRROR_URL: "git@github.com/EpitechPromo2028/B-DOP-200-PAR-2-1-chocolatine-hyelim.jeon.git"
  EXECUTABLES: "./main.c"

jobs:
  check_coding_style:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/epitech/coding-style-checker:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Coding Style Checker
        run: check.sh $(pwd) $(pwd) > coding-style-report.log     


  check_program_compilation:
    runs-on: ubuntu-latest
    needs: check_coding_style
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make
      - run: make clean
      - name: Check for executables
        run: |
          for exe in $EXECUTABLES; do
            if [ ! -x "$exe" ]; then
              echo "::error file=$exe::Executable file not found or not executable."
              exit 1
            fi
          done
      # - run: for i in $EXECUTABLES; do if [ ! -x $i ]; then exit 1; fi; done


  run_tests:
    needs: check_program_compilation
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: make run_tests


  push_to_mirror:
    needs: run_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}